name: muni_incidencias
description: "Aplicación Flutter para reportar incidencias en la Municipalidad"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # --- Firebase ---
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2

  # --- PDF y archivos ---
  pdf: ^3.10.4
  open_filex: ^4.5.0
  path_provider: ^2.1.3
  excel: ^3.0.0

  # --- Gráficos (para reportes) ---
  syncfusion_flutter_charts: ^26.1.45  # ✅ Corrige los errores de markNeedsBuild, etc.

  # --- UI y utilidades ---
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  qr_flutter: ^4.1.0
  uuid: ^4.5.1
  mobile_scanner: ^4.0.1
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  
  intl: ^0.19.0  # ✅ Ahora sí compatible con syncfusion_flutter_charts ^26.1.45+

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700